// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuXSWWARqJYNvz2sBQIRizJIw5xaogu0U',
    appId: '1:486140167563:web:21f286cb336c61dfae5b8e',
    messagingSenderId: '486140167563',
    projectId: 'kealthy-90c55',
    authDomain: 'kealthy-90c55.firebaseapp.com',
    databaseURL: 'https://kealthy-90c55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kealthy-90c55.appspot.com',
    measurementId: 'G-927BYEQJ26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtCIdSOs_cpsz6TLXcJaMloWKFJcB2BlM',
    appId: '1:486140167563:android:9f00064ee0e497e7ae5b8e',
    messagingSenderId: '486140167563',
    projectId: 'kealthy-90c55',
    databaseURL: 'https://kealthy-90c55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kealthy-90c55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8Rza2XPXSEBOzTbkGxsUpGwV1EYKNfg',
    appId: '1:486140167563:ios:08d054e6b18c02c1ae5b8e',
    messagingSenderId: '486140167563',
    projectId: 'kealthy-90c55',
    databaseURL: 'https://kealthy-90c55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kealthy-90c55.appspot.com',
    iosBundleId: 'com.cotolore.kealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm8Rza2XPXSEBOzTbkGxsUpGwV1EYKNfg',
    appId: '1:486140167563:ios:f352ff88771c91f2ae5b8e',
    messagingSenderId: '486140167563',
    projectId: 'kealthy-90c55',
    databaseURL: 'https://kealthy-90c55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kealthy-90c55.appspot.com',
    iosBundleId: 'com.example.kealthyFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1MUoakZ0mm8WeFv_GK9k_zAWdGk5r1hA',
    appId: '1:486140167563:web:eff6a6b96b8c361dae5b8e',
    messagingSenderId: '486140167563',
    projectId: 'kealthy-90c55',
    authDomain: 'kealthy-90c55.firebaseapp.com',
    databaseURL: 'https://kealthy-90c55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kealthy-90c55.appspot.com',
    measurementId: 'G-037BHS1KRK',
  );

}